// 政治面貌
export const columnsPolitical = [
  { text: "群众", id: "1", value: "1" },
  { text: "中国共产党员", id: "2", value: "2" },
  { text: "共青团团员", id: "3", value: "3" },
  { text: "其他党派人士", id: "4", value: "4", needFilling: true }, // 需要填空
];
// 文化程度
export const columnsLiteracy = [
  { text: "识字", id: "1", value: "1", skip: ["10", "11"] },
  { text: "小学", id: "2", value: "2", skip: ["10", "11"] },
  { text: "初中", id: "3", value: "3", skip: ["10", "11"] },
  { text: "普高/职高", id: "4", value: "4", skip: ["10", "11"] },
  { text: "大专", id: "5", value: "5", skip: [] },
  { text: "本科", id: "5", value: "5", skip: [] },
  { text: "研究生", id: "6", value: "6", skip: [] },
];
// 职业
export const columnsOccupation = [
  { text: "公职人员", id: "1", value: "1", skip: [] },
  { text: "教师", id: "2", value: "2", skip: [] },
  { text: "外出干部", id: "3", value: "3", skip: [] },
  { text: "科技人员", id: "4", value: "4", skip: ["15"] },
  { text: "企业负责人", id: "5", value: "5", skip: ["15"] },
  { text: "其他", id: "6", value: "6", skip: ["15"] },
];
// 56个民族
export const columnsNation = [
  { text: "汉族", value: "1" },
  { text: "黎族", value: "2" },
  { text: "苗族", value: "3" },
  { text: "壮族", value: "4" },
  { text: "回族", value: "5" },
  { text: "彝族", value: "6" },
  { text: "侗族", value: "7" },
  { text: "瑶族", value: "8" },
  { text: "满族", value: "9" },
  { text: "维吾尔族", value: "10" },
  { text: "土家族", value: "11" },
  { text: "蒙古族", value: "12" },
  { text: "藏族", value: "13" },
  { text: "布依族", value: "14" },
  { text: "朝鲜族", value: "15" },
  { text: "白族", value: "16" },
  { text: "哈尼族", value: "17" },
  { text: "哈萨克族", value: "18" },
  { text: "傣族", value: "19" },
  { text: "畲族", value: "20" },
  { text: "傈僳族", value: "21" },
  { text: "仡佬族", value: "22" },
  { text: "东乡族", value: "23" },
  { text: "高山族", value: "24" },
  { text: "拉祜族", value: "25" },
  { text: "水族", value: "26" },
  { text: "佤族", value: "27" },
  { text: "纳西族", value: "28" },
  { text: "羌族", value: "29" },
  { text: "土族", value: "30" },
  { text: "仫佬族", value: "31" },
  { text: "锡伯族", value: "32" },
  { text: "柯尔克孜族", value: "33" },
  { text: "达斡尔族", value: "34" },
  { text: "景颇族", value: "35" },
  { text: "毛南族", value: "36" },
  { text: "撒拉族", value: "37" },
  { text: "布朗族", value: "38" },
  { text: "塔吉克族", value: "39" },
  { text: "阿昌族", value: "40" },
  { text: "普米族", value: "41" },
  { text: "鄂温克族", value: "42" },
  { text: "怒族", value: "43" },
  { text: "京族", value: "44" },
  { text: "基诺族", value: "45" },
  { text: "德昂族", value: "46" },
  { text: "保安族", value: "47" },
  { text: "俄罗斯族", value: "48" },
  { text: "裕固族", value: "49" },
  { text: "乌孜别克族", value: "50" },
  { text: "门巴族", value: "51" },
  { text: "鄂伦春族", value: "52" },
  { text: "独龙族", value: "53" },
  { text: "塔塔尔族", value: "54" },
  { text: "赫哲族", value: "55" },
  { text: "珞巴族", value: "56" },
];
